name: Create GKE using IAC

on:
 workflow_dispatch:
   inputs:
    branch: 
      description: 'Branch to use'
      required: true
      default: 'main'
      type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the specific branch
        uses: actions/checkout@v3
        with: 
          ref: ${{ github.event.inputs.branch }}
      
      - name: Setup GCloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with: 
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY}}
          export_default_credentails : false

      - name: Install terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Terraform Init
        run: terraform init
        env: 
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Terrraform plan
        run: terraform plan -var-file="terraform.tfvars"
        env: 
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Terraform Apply
        run: terraform apply -var-file="terraform.tfvars" -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

